### PR TITLE
rendering one picture hosted on AWS in my gallery

### PR DESCRIPTION
**Pull request by manuelreneduran**

### CODE REVIEW

**Review by hegitsit — APPROVED** [review]
Everything checks out awesome work man.

**Review by hegitsit — COMMENTED** [review]
Just curious will this index.css be the one place you are keeping all of your styles?

**Comment by manuelreneduran** [comment]
> Just curious will this index.css be the one place you are keeping all of your styles?

I am -- is that not standard practice?

**Comment by hegitsit** [comment]
It's perfectly ok for us. But just as you css gets bigger you would want to break it out into a separate file. You eventually want to get to the place where you have one component and its own style sheet.

**Comment by manuelreneduran** [comment]
That makes a lot of sense. I'm thinking that's as big as the style sheet is going to get for me but I'll keep it in mind it gets any bigger.

**Comment by manuelreneduran** [comment]
image
Here's what it looks like at the moment.

**Comment by camper2018** [comment]
Looks awesome.

**Review by camper2018 — APPROVED** [review]

**Pull request merged**
