### PR TITLE
initialized folders

### LINKED ISSUE #2: Test
Test

### PR DESCRIPTION
**Pull request by manuelreneduran**
Test closes #2

### CODE REVIEW

**Comment by hegitsit** [comment]
Test approved!

**Comment by camper2018** [comment]
looks good but i think you need to add id parameter to your api .

**Comment by manuelreneduran** [comment]
> looks good but i think you need to add id parameter to your api .

Nice catch, I'll make sure to add that.

**Comment by manuelreneduran** [comment]
closes #2

**Pull request merged**
